type Client {
  id: ID
  address: String
  blocked: String
  cellPhone: String
  channel: String
  clientId: String
  country: String
  customerGroup: CustomerGroup
  customerSchema: Int
  distrChan: String
  division: String
  fiscalCode1: String
  fiscalCode2: String
  frequency: Boolean
  frequencyDays: String
  idPortfolio: String
  immediateDelivery: Boolean
  industryCode: String
  industryCode1: String
  isEnrollment: Boolean
  name: String
  name2: String
  office: String
  paymentCondition: String
  paymentMethods: [PaymentMethod]
  portfolio: [Portfolio]
  priceGroup: String
  priceList: String
  routeId: String
  salesOrg: String
  supplyCenter: String
  updateDate: UpdateDate
  vendorGroup: String
}

type UpdateDate {
  date: String
}
